[tool.poetry]
name = "tetris"
version = "0.2.0-alpha.0"
description = "i have too much free time"
authors = ["Sofia \"dzshn\" N. L. <zshn@pm.me>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9,<3.11"
"discord.py" = {git = "https://github.com/Rapptz/discord.py"}
numpy = "^1.21.2"
psutil = "^5.8.0"
yade = {git = "https://github.com/dzshn/yade", rev = "main"}
aioredis = "^2.0.0"
fakeredis = "^1.6.1"
redis = "^3.5.3"
hiredis = "^2.0.0"
PyYAML = "^6.0"

[tool.poetry.dev-dependencies]
flake8 = "^4.0.1"
isort = "^5.9.3"
black = "^21.9b0"

[tool.black]
skip-string-normalization = true

[tool.isort]
profile = "google"
force_sort_within_sections = false

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
